name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-security:
    name: Build · Test (${{ matrix.node-version }}, ${{ matrix.os }}) · Security
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18, 20, 21]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests & Collect coverage
        env:
          TEST_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }} # Required for integration tests
          TEST_GOOGLE_API_KEY: ${{ secrets.TEST_GOOGLE_API_KEY }}
          TEST_ANTHROPIC_API_KEY: ${{ secrets.TEST_ANTHROPIC_API_KEY }}
          TEST_OLLAMA_HOST: http://localhost:11434 # Ollama usually runs on localhost for tests
        run: npm run test -- --coverage --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
        if: matrix.node-version == 18 && matrix.os == 'ubuntu-latest' # Only upload once

      - name: Type check
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Test CLI commands (on Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          node dist/src/cli.js --help
          node dist/src/cli.js setup --help
          node dist/src/cli.js validate-config --help

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true # Allow build to pass even with moderate issues for PRs

